### ISSUE TITLE
Guzzle 6

### ISSUE THREAD

**Issue by kduma** [php-tmdb/api#108]
Is it possible to make it work with Guzzle 6?

**Comment by wtfzdotnet** [comment]
Hi, 

This is certainly possible, sorry for getting back so late but I'm still busy moving in to another apartment so I'm quite preoccupied.

I hope to get in this week but still won't have an internet connection there until they come and fix my cable. I'll try to see to it soon.

**Comment by wtfzdotnet** [comment]
Haven't forgotten about this issue, just been overloaded with my new job and apartment, I'll see to it tonight or tomorrow what the possibilities are.

Thanks

**Comment by wtfzdotnet** [comment]
Just looked into this, it's possible, it however requires the log and cache subscribers to be removed from the `composer.json` of the library ( to be clean, I could leave them there but it would be nonsense to require them if you never use them ). I need to look into how to solve this properly with BC, as removing these dependencies would break `5.*` usage ( the default caching implementation ).

I'm really shorthanded on time lately, so if this issue is a big pain for you I'd kindly ask you to figure this out, and make a pull request to solve it.

**Comment by wtfzdotnet** [comment]
Work is in progress for this, see #111

**Comment by wtfzdotnet** [comment]
Guzzle 6 will be available from 2.1 which I will release soon if travis doesn't find anything to sniff.
