### ISSUE TITLE
Config option for cache lifetime

### ISSUE THREAD

**Issue by cnkt** [php-tmdb/api#150]
Is there a way to set cache lifetime? I want to cache every request for infinite time until i clear the cache directory.

Thanks.

**Comment by wtfzdotnet** [comment]
First off all, sorry for having your issue open without a response at all! 

Without having taken a look at the code again since ( which I respectfully would but... ), I think the easiest way to accomplish this in your case is modifying the responses with certain caching. If done correctly and slightly variably, this would give you a lot more power over your cache based on regex patterns or whatever you fancy.

Otherwise you could always implement a custom cache provider with a set lifetime and inject that to the client.
