### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by costapombo** [php-tmdb/api#178]
What happens when you reach maximum requests ? (40 / 10 sec) 
What happens when is not returned 200 code ? 

Also  
`->getPeopleApi()->getPerson(id)`
is very slow

**Comment by wtfzdotnet** [comment]
You can find the answers to your questions here;

- https://github.com/php-tmdb/api/blob/2.1/lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php#L53 this is how we handle the rate limiting
- https://github.com/php-tmdb/api/blob/2.1/lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php#L145 this is how we handle exceptions coming from the api

Are you making use of a memory store as a cache pool instead of being written onto disk? This will make significant performance benefits.
