### ISSUE TITLE
Implement `account_states` for TV related objects.

### ISSUE THREAD

**Issue by wtfzdotnet** [php-tmdb/api#80]
http://docs.themoviedb.apiary.io/#reference/tv/tvidaccountstates

http://docs.themoviedb.apiary.io/#reference/tv-seasons/tvidseasonseasonnumberaccountstates

http://docs.themoviedb.apiary.io/#reference/tv-episodes/tvidseasonseasonnumberepisodeepisodenumberaccountstates

**Comment by wtfzdotnet** [comment]
@wagnered up for some more? ;)

**Comment by wagnered** [comment]
I think I would like to get back to implementing TV Content Ratings from both the Tmdb and TvDb APIs into Ampache.  It's displaying the value in the UI that may be the most difficult because jquery is used to display/hide/edit the values.  Ampache's not documented well and doesn't use the Controller-Model-View framework, so it's difficult to reverse engineer : ' >
